{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-4231",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "ibm",
            "product": {
              "product_data": [
                {
                  "product_name": "cognos_analytics",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "11.0.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.0.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.1",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.1.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.2",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.2.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.3",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.3.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.4",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.4.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.5",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.6",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.7",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.8",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.9",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.10",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.10.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.11",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.11.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.12",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.0.13",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.1.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.1.1",
                        "version_affected": "="
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-352"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/159356",
          "name": "ibm-cognos-cve20194231-csrf (159356)",
          "refsource": "XF",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://security.netapp.com/advisory/ntap-20200103-0003/",
          "name": "https://security.netapp.com/advisory/ntap-20200103-0003/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://www.ibm.com/support/pages/node/1138588",
          "name": "https://www.ibm.com/support/pages/node/1138588",
          "refsource": "CONFIRM",
          "tags": [
            "Patch",
            "Vendor Advisory"
          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Cognos Analytics 11.0 and 11.1 is vulnerable to cross-site request forgery which could allow an attacker to execute malicious and unauthorized actions transmitted from a user that the website trusts. IBM X-Force ID: 159356."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "11.0.0",
            "versionEndIncluding": "11.0.12"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:-:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:fix_pack_1:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:fix_pack_2:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "11.1.0",
            "versionEndExcluding": "11.1.4.0"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "NONE",
        "baseScore": 4.3
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 2.9,
      "acInsufInfo": false,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": true
    }
  },
  "publishedDate": "2019-12-20T17:15Z",
  "lastModifiedDate": "2020-01-03T11:15Z"
}