{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2020-8315",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "3.6.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.1",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.2",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.3",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.4",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.5",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.6",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.7",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.8",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.9",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.6.10",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.1",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.2",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.3",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.4",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.5",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.7.6",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.8.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.8.0b1",
                        "version_affected": "="
                      },
                      {
                        "version_value": "3.8.1",
                        "version_affected": "="
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugs.python.org/issue39401",
          "name": "https://bugs.python.org/issue39401",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Vendor Advisory"
          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In Python (CPython) 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1, an insecure dependency load upon launch on Windows 7 may result in an attacker's copy of api-ms-win-core-path-l1-1-0.dll being loaded and used instead of the system's copy. Windows 8 and later are unaffected."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "3.6.0",
            "versionEndIncluding": "3.6.10"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "3.7.0",
            "versionEndIncluding": "3.7.6"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "3.8.0",
            "versionEndIncluding": "3.8.1"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "NONE",
        "baseScore": 4.3
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 2.9,
      "acInsufInfo": false,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": true
    }
  },
  "publishedDate": "2020-01-28T19:15Z",
  "lastModifiedDate": "2020-02-01T17:13Z"
}