{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-4343",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "ibm",
            "product": {
              "product_data": [
                {
                  "product_name": "cognos_analytics",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "11.0.0",
                        "version_affected": "="
                      },
                      {
                        "version_value": "11.1.0",
                        "version_affected": "="
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-200"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/161422",
          "name": "ibm-cognos-cve20194343-cors (161422)",
          "refsource": "XF",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ]
        },
        {
          "url": "https://security.netapp.com/advisory/ntap-20200110-0002/",
          "name": "https://security.netapp.com/advisory/ntap-20200110-0002/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://www.ibm.com/support/pages/node/1146424",
          "name": "https://www.ibm.com/support/pages/node/1146424",
          "refsource": "CONFIRM",
          "tags": [
            "Vendor Advisory"
          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Cognos Analytics 11.0 and 11.1 allows overly permissive cross-origin resource sharing which could allow an attacker to transfer private information. An attacker could exploit this vulnerability to access content that should be restricted. IBM X-Force ID: 161422."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "SINGLE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 4.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.0,
      "impactScore": 2.9,
      "acInsufInfo": false,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2019-12-30T16:15Z",
  "lastModifiedDate": "2020-01-10T11:15Z"
}